import type { User } from "@/types/auth"

// Generate mock data for testing
export const mockUsers: User[] = [
  {
    oid: "oid-123456-abcdef-1",
    nombre: "Juan Pérez",
    email: "juan.perez@asofarma.com",
    departamentoNombre: "Recursos Humanos",
    rolNombre: "Administrador",
    cargoNombre: "Gerente de RRHH",
    // Legacy properties for backward compatibility
    departamento: "Recursos Humanos",
    rol: "Administrador",
    cargo: "Gerente de RRHH",
  },
  {
    oid: "oid-123456-abcdef-2",
    nombre: "María López",
    email: "maria.lopez@asofarma.com",
    departamentoNombre: "Finanzas",
    rolNombre: "Miembro",
    cargoNombre: "Analista Financiero",
    departamento: "Finanzas",
    rol: "Miembro",
    cargo: "Analista Financiero",
  },
  {
    oid: "oid-123456-abcdef-3",
    nombre: "Carlos Rodríguez",
    email: "carlos.rodriguez@asofarma.com",
    departamentoNombre: "Tecnología",
    rolNombre: "Administrador",
    cargoNombre: "Desarrollador Senior",
    departamento: "Tecnología",
    rol: "Administrador",
    cargo: "Desarrollador Senior",
  },
  {
    oid: "oid-123456-abcdef-4",
    nombre: "Ana Martínez",
    email: "ana.martinez@asofarma.com",
    departamentoNombre: "Recursos Humanos",
    rolNombre: "Visualizador",
    cargoNombre: "Asistente de RRHH",
    departamento: "Recursos Humanos",
    rol: "Visualizador",
    cargo: "Asistente de RRHH",
  },
  {
    oid: "oid-123456-abcdef-5",
    nombre: "Roberto Sánchez",
    email: "roberto.sanchez@asofarma.com",
    departamentoNombre: "Ventas",
    rolNombre: "Miembro",
    cargoNombre: "Director Comercial",
    departamento: "Ventas",
    rol: "Miembro",
    cargo: "Director Comercial",
  },
  {
    oid: "oid-123456-abcdef-6",
    nombre: "Laura Gómez",
    email: "laura.gomez@asofarma.com",
    departamentoNombre: "Marketing",
    rolNombre: "Visualizador Departamental",
    cargoNombre: "Coordinador de Marketing",
    departamento: "Marketing",
    rol: "Visualizadordepartamental",
    cargo: "Coordinador de Marketing",
  },
  {
    oid: "oid-123456-abcdef-7",
    nombre: "Miguel Fernández",
    email: "miguel.fernandez@asofarma.com",
    departamentoNombre: "Tecnología",
    rolNombre: "Miembro",
    cargoNombre: "Arquitecto de Software",
    departamento: "Tecnología",
    rol: "Miembro",
    cargo: "Arquitecto de Software",
  },
  {
    oid: "oid-123456-abcdef-8",
    nombre: "Patricia Díaz",
    email: "patricia.diaz@asofarma.com",
    departamentoNombre: "Operaciones",
    rolNombre: "Visualizador",
    cargoNombre: "Supervisor de Planta",
    departamento: "Operaciones",
    rol: "Visualizador",
    cargo: "Supervisor de Planta",
  },
  {
    oid: "oid-123456-abcdef-9",
    nombre: "Javier Torres",
    email: "javier.torres@asofarma.com",
    departamentoNombre: "Legal",
    rolNombre: "Visualizador Departamental",
    cargoNombre: "Abogado",
    departamento: "Legal",
    rol: "Visualizadordepartamental",
    cargo: "Abogado",
  },
  {
    oid: "oid-123456-abcdef-10",
    nombre: "Sofía Ramírez",
    email: "sofia.ramirez@asofarma.com",
    departamentoNombre: "Finanzas",
    rolNombre: "Administrador",
    cargoNombre: "Controller",
    departamento: "Finanzas",
    rol: "Administrador",
    cargo: "Controller",
  },
]
